### ISSUE TITLE
loader.js error Ubuntu 20.04 with ffmpeg 4.4.2

### ISSUE THREAD

**Issue by Kazz3r24** [binair-io/h265ize#1]
Just came from FallingSnow's repo which is sadly collecting dust. I saw your post and went to check out your fork, unfortunately it doesn't run period. Not sure if I did something incorrectly, but I cloned the repo to /opt/ copied the settings.examply.json to settings.json and edited it (correctly or not I can't determine) - but now when trying to run it I get the following 

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/h265ize/h265ize:11:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

Here is my settings.json (it's modified to fit my needs)

`cat settings.json
{
#    "HOW TO USE": "Copy this file to settings.json and modify the settings below.",
    "destination": "/tmp",
    "preset": "medium",
    "as-preset": "none",
    "native-language": "eng",
    "output-format": "mkv",
    "extra-options": "",
    "quality": 24,
    "video-bitrate": 0,
    "preview-length": 30000,
    "accurate-timestamps": false,
    "he-audio": false,
    "force-he-audio": false,
    "downmix-he-audio": false,
    "override": false,
    "preview": false,
    "sample": false,
    "multi-pass": 0,
    "stats": true,
    "verbose": true,
    "bitdepth": 10,
    "screenshots": false,
    "normalize-level": 0,
    #"scale": ,
    "debug": false,
    "delete": false
}`

Then when attempting to run a conversion I am running the command as follows (this is from within the media's directory not opt)

`/opt/h265ize/h265ize ../21\ Jump\ Street/ -d h265/`

I debated removing the -d argument as it's an h265 argument which I wasn't sure was covered in settings.json (documentation needs work).

I myself have been using h265ize for years, and I know there are many other users out there trying to use it as well, you'd be a Godsend if you revive this.

**Comment by binair-io** [comment]
I don't think copying and pasting the fork's changes will do the trick as it's not packaged. Referenced modules (or specific versions) might not be installed. 

Would you like to go to the root folder of the downloaded fork in a command window and do `npm i` in that folder? For instance: '/opt/h265ize' It will then download and install the required packages. See if that works.

If more people want to use this fork I might publish a npm package for it. Documentation indeed needs work. Will also put more effort in this project depending on the demand :-)

I'll keep a closer eye on this thread so I can give you a faster update to get it resolved.

**Comment by Kazz3r24** [comment]
Thank you for getting back to me, I am trying your suggestion with `npm i`  in that folder. I had done that with the previous fork, just not this one. It seems to be running for the moment - though I had just run into another error but didn't catch it due to `screen` terminating before I got a good look. After rerunning the command again without `screen` so I could catch the error, it seems to be running fine for the moment. We'll see if it makes it through the whole series without issue.

*UPDATE* still no joy, the encoding starts but ffmpeg exits. I've attached the h265ize.log for review.
[h265ize.log](https://github.com/binair-io/h265ize/files/8838191/h265ize.log)

**Comment by binair-io** [comment]
I'm seeing this: `/mnt/Echo/TV Shows/21 Jump Street/h264/Season 4/21 Jump Street.S04E01.Draw the Line.mkv: No such file or directory` Can you try updating ffmpeg to the latest version? I've also had issues until I updated to the last version. You're using version 4, they're currently at 7. https://launchpad.net/ubuntu/+source/ffmpeg

**Comment by Kazz3r24** [comment]
Ok, I'll give that a try - if that's what it's sending over to my Plex server, it wouldn't be found either way though, the mount point Plex should be looking for is /mnt/Foxtrot/TV Shows/etc/etc/.

Unfortunately it looks like I'm already on the latest version of ffmpeg.

It's alright, not a huge deal. Just a bummer that this became abandonware. I did see the author of h265ize is working on something new now NMMES, looks like it's the same thing as this only maybe more robust? I wasn't able to get it working either lol.

![image](https://user-images.githubusercontent.com/15070472/172076857-4e3b2892-a483-4d95-953e-20ee048952be.png)

![image](https://user-images.githubusercontent.com/15070472/172076874-cf0839ba-9663-491f-b424-763c5c2779fe.png)
